"use client";
import { useEffect, useState } from "react";

type DailyBadge = { days: number; name: string; description: string; unlocked: boolean };
type DailyHistory = { day: string; score: string; margin: number; won: boolean };
type Profile = { slug: string; displayName: string; isPublic: boolean; own: boolean; stats: { wins: number; losses: number; seriesPlayed: number; games: number; savedMatches: number; pointsFor: number; pointsAgainst: number; winRate: number; daily: { daysPlayed: number; attempts: number; wins: number; currentStreak: number; bestStreak: number; bestMargin: number | null; badges: DailyBadge[]; history: DailyHistory[] } } };
const button = "rounded-xl border px-4 py-2 text-sm font-semibold hover:bg-foreground/10 disabled:opacity-40";
export default function ArenaProfile({ slug }: { slug?: string }) {
  const [profile, setProfile] = useState<Profile | null>(null), [name, setName] = useState(""), [error, setError] = useState(""), [saved, setSaved] = useState(false);
  useEffect(() => { fetch(`/api/arena-profile${slug ? `?slug=${encodeURIComponent(slug)}` : ""}`, { cache: "no-store" }).then(async r => { const data = await r.json(); if (!r.ok) throw Error(data.error); setProfile(data); setName(data.displayName); }).catch(e => setError(e.message)); }, [slug]);
  async function save() { setError(""); setSaved(false); const response = await fetch("/api/arena-profile", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ displayName: name, isPublic: profile?.isPublic }) }); const data = await response.json(); if (!response.ok) return setError(data.error); setProfile(p => p ? { ...p, ...data } : p); setSaved(true); }
  if (error) return <main className="mx-auto max-w-4xl py-10"><p role="alert">{error}</p></main>;
  if (!profile) return <main className="mx-auto max-w-4xl py-10"><p>Loading arena profile…</p></main>;
  const shareUrl = typeof window === "undefined" ? "" : `${window.location.origin}/full-court/coach/${profile.slug}`;
  return <main className="mx-auto max-w-4xl py-10 space-y-6">
    <section className="rounded-3xl border border-orange-500/30 bg-gradient-to-br from-orange-500/15 via-card to-card p-8">
      <p className="text-xs font-bold uppercase tracking-[.25em] text-cyan-300">FIVEOUT coach profile</p><h1 className="mt-2 text-4xl font-black">{profile.displayName}</h1><p className="mt-2 text-foreground/60">Your saved match record</p>
      <div className="mt-8 grid grid-cols-2 gap-3 sm:grid-cols-4">{[["Saved matches", profile.stats.savedMatches], ["Challenge record", `${profile.stats.wins}–${profile.stats.losses}`], ["Win rate", `${profile.stats.winRate}%`], ["Series games", profile.stats.games]].map(([label, value]) => <div key={label} className="rounded-2xl border bg-background/60 p-4"><p className="text-xs uppercase text-foreground/50">{label}</p><p className="mt-1 text-2xl font-black">{value}</p></div>)}</div>
      <p className="mt-5 text-sm text-foreground/60">Total points: {profile.stats.pointsFor} for · {profile.stats.pointsAgainst} against</p>
    </section>
    <section className="rounded-3xl border border-violet-400/25 bg-gradient-to-br from-violet-500/10 via-card to-card p-8">
      <div className="flex flex-wrap items-end justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-[.25em] text-violet-300">Daily Challenge</p><h2 className="mt-2 text-2xl font-black">Daily record</h2></div>{profile.own && <a href="/full-court/daily" className="text-sm font-bold text-cyan-300">Play today →</a>}</div>
      <div className="mt-6 grid grid-cols-2 gap-3 sm:grid-cols-4">{[["Days played", profile.stats.daily.daysPlayed], ["Current streak", `${profile.stats.daily.currentStreak} days`], ["Best streak", `${profile.stats.daily.bestStreak} days`], ["Best margin", profile.stats.daily.bestMargin == null ? "—" : `${profile.stats.daily.bestMargin > 0 ? "+" : ""}${profile.stats.daily.bestMargin}`]].map(([label, value]) => <div key={label} className="rounded-2xl border bg-background/60 p-4"><p className="text-xs uppercase text-foreground/50">{label}</p><p className="mt-1 text-2xl font-black">{value}</p></div>)}</div>
      <div className="mt-7"><h3 className="font-black">Streak badges</h3><div className="mt-3 grid gap-3 sm:grid-cols-3">{profile.stats.daily.badges.map(badge => <div key={badge.days} className={`rounded-2xl border p-4 ${badge.unlocked ? "border-violet-400/40 bg-violet-400/10" : "border-white/10 opacity-45"}`}><p className="text-2xl">{badge.unlocked ? "🏆" : "🔒"}</p><p className="mt-2 font-black">{badge.name}</p><p className="mt-1 text-xs text-foreground/55">{badge.description}</p></div>)}</div></div>
      <div className="mt-7"><h3 className="font-black">Recent Daily results</h3>{profile.stats.daily.history.length ? <div className="mt-3 divide-y divide-white/10 rounded-2xl border border-white/10">{profile.stats.daily.history.map(run => <div key={run.day} className="grid grid-cols-[1fr_auto_auto] items-center gap-4 p-3 text-sm"><span className="text-foreground/60">{run.day}</span><b>{run.score}</b><span className={run.won ? "text-emerald-400" : "text-foreground/50"}>{run.margin > 0 ? "+" : ""}{run.margin}</span></div>)}</div> : <p className="mt-3 text-sm text-foreground/50">No Daily Challenge results yet.</p>}</div>
    </section>
    {profile.own && <section className="rounded-2xl border p-5 space-y-4"><h2 className="text-xl font-bold">Profile settings</h2><label className="block text-sm font-semibold">Coach name<input className="mt-2 block w-full rounded-xl border bg-background p-3" value={name} onChange={e => setName(e.target.value)} /></label><label className="flex gap-2 text-sm"><input type="checkbox" checked={profile.isPublic} onChange={e => setProfile({ ...profile, isPublic: e.target.checked })} /> Public profile</label><div className="flex flex-wrap gap-3"><button className={button} onClick={() => void save()}>Save profile</button><button className={button} disabled={!profile.isPublic} onClick={() => navigator.clipboard.writeText(shareUrl)}>Copy public link</button></div>{saved && <p className="text-sm text-emerald-500">Profile saved.</p>}</section>}
  </main>;
}
